version: 2.1

orbs:
  nx: nrwl/nx@1.6.1

parameters:
  sample:
    type: enum
    enum: ['hello', 'world']
    default: 'hello'

jobs:
  setup:
    docker:
      - image: cimg/node:16.18.1
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
            - ../.cache

  e2e:
    docker:
      - image: cypress/base:16.18.1
    steps:
      - checkout
      - restore_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
      - run: export A=world
      - when:
          condition:
            equal: [$A, << pipeline.parameters.sample >>]
          steps:
            - run: echo "cheese"

workflows:
  pipeline:
    jobs:
      - setup
      - e2e:
          requires:
            - setup
